// vue-example/src/components/Arkose.vue
<template>
  <div
    v-if="mode === 'inline' && selector"
    :id="selector.replace(/^#/, '')"
  />
</template>

<script setup>
import { onMounted, onBeforeUnmount } from 'vue';

const props = defineProps({
  publicKey: { type: String, required: true },
  mode: { type: String, default: '' },
  selector: { type: String, default: null },
  nonce: { type: String, default: '' },
});

const emit = defineEmits([
  'ready', 'shown', 'show', 'suppress', 'completed',
  'reset', 'hide', 'error', 'failed',
]);

let enforcement = null;
const scriptId = `arkose-script-${props.publicKey}`;

const run = () => enforcement?.run();

defineExpose({ run });

const setupEnforcement = (myEnforcement) => {
  enforcement = myEnforcement;
  enforcement.setConfig({
    selector: props.selector,
    mode: props.mode,
    onReady: () => emit('ready'),
    onShown: () => emit('shown'),
    onShow: () => emit('show'),
    onSuppress: () => emit('suppress'),
    onCompleted: (response) => emit('completed', response.token),
    onReset: () => emit('reset'),
    onHide: () => emit('hide'),
    onError: (response) => emit('error', response?.error?.error),
    onFailed: (response) => emit('failed', response),
  });
};

onMounted(() => {
  window.setupEnforcement = setupEnforcement;

  if (document.getElementById(scriptId)) {
    return;
  }

  const script = document.createElement('script');
  script.id = scriptId;
  script.src = `https://client-api.arkoselabs.com/v2/${props.publicKey}/api.js`;
  script.setAttribute('data-callback', 'setupEnforcement');
  script.async = true;
  script.onerror = () => emit('error', 'Script load failed');
  if (props.nonce) {
    script.setAttribute('data-nonce', props.nonce);
  }
  document.body.appendChild(script);
});

onBeforeUnmount(() => {
  if (window.setupEnforcement === setupEnforcement) {
    delete window.setupEnforcement;
  }
  const el = document.getElementById(scriptId);
  if (el) el.remove();
});
</script>

// react-example/src/components/Arkose.jsx
import { useEffect, useRef, useCallback, forwardRef, useImperativeHandle } from 'react';

const Arkose = forwardRef(function Arkose({
  publicKey,
  mode,
  selector,
  nonce,
  onReady = () => {},
  onShown = () => {},
  onShow = () => {},
  onSuppress = () => {},
  onCompleted = () => {},
  onReset = () => {},
  onHide = () => {},
  onError = () => {},
  onFailed = () => {},
}, ref) {
  const enforcementRef = useRef(null);
  const scriptId = `arkose-script-${publicKey}`;

  useImperativeHandle(ref, () => ({
    run: () => enforcementRef.current?.run(),
  }));

  const callbacksRef = useRef({
    onReady, onShown, onShow, onSuppress, onCompleted,
    onReset, onHide, onError, onFailed,
  });
  callbacksRef.current = {
    onReady, onShown, onShow, onSuppress, onCompleted,
    onReset, onHide, onError, onFailed,
  };

  const setupEnforcement = useCallback((myEnforcement) => {
    enforcementRef.current = myEnforcement;
    myEnforcement.setConfig({
      selector,
      mode,
      onReady: () => callbacksRef.current.onReady(),
      onShown: () => callbacksRef.current.onShown(),
      onShow: () => callbacksRef.current.onShow(),
      onSuppress: () => callbacksRef.current.onSuppress(),
      onCompleted: (response) => callbacksRef.current.onCompleted(response.token),
      onReset: () => callbacksRef.current.onReset(),
      onHide: () => callbacksRef.current.onHide(),
      onError: (response) => callbacksRef.current.onError(response?.error?.error),
      onFailed: (response) => callbacksRef.current.onFailed(response),
    });
  }, [selector, mode]);

  useEffect(() => {
    window.setupEnforcement = setupEnforcement;

    const existingScript = document.getElementById(scriptId);
    if (existingScript) {
      existingScript.remove();
    }

    const script = document.createElement('script');
    script.id = scriptId;
    script.src = `https://client-api.arkoselabs.com/v2/${publicKey}/api.js`;
    script.setAttribute('data-callback', 'setupEnforcement');
    script.async = true;
    script.onerror = () => callbacksRef.current.onError('Script load failed');
    if (nonce) {
      script.setAttribute('data-nonce', nonce);
    }
    document.body.appendChild(script);

    return () => {
      if (window.setupEnforcement === setupEnforcement) { delete window.setupEnforcement; }
      const el = document.getElementById(scriptId);
      if (el) el.remove();
    };
  }, [publicKey, nonce, setupEnforcement]);

  if (mode === 'inline' && selector) {
    return <div id={selector.replace(/^#/, '')} />;
  }
  return null;
});

export default Arkose;
